---
title: "diary ✦ arka ruins"
output: 
  html_document:
    fig_caption: FALSE
    includes:
      in_header: header.html
      after_body: footer.html
css: "indexstyle.css"
---

:::{.container}

```{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('menu.html')
```
```
This part of my site is less like a "blog" and more like a "brain dump" since I feel pretty strongly about [btxx's concept of making a "brain dump" in lieu of a "blog"](https://btxx.org/posts/dump/). I also used to host this on [zonelets](https://zonelets.net/) with the static generator [zoner](https://ryantrawick.itch.io/zoner), but I write everything in Rmd format right now.

Older posts are longer form and more formal since I wasn't really sure what I wanted to do with this part of my site, but I've moved to using it more casually to expand on random ideas... Don't take me too seriously.

* **April 22, 2024:** [Ditch Google Docs and Get a Blog](diary/gdocs-blog.html) -- I think everyone should stop putting their interesting thoughts and opinions in Google docs and just get a blog already.
* **March 2, 2024:** [Making a site in RStudio](diary/rmarkdown-ssg.html) -- My experiences and challenges with brute-forcing a data science IDE to make a website.
* **March 1, 2024:** [2024 Yearly themes](diary/2024-themes.html) -- Blog about yearly themes and general ideas.
* **February 6, 2023:** [Year of the Water Rabbit](diary/water-rabbit.html) -- My hopes and aspirations for 2023.
* **June 15, 2022:** [Ethics of Microexpression Theory](diary/microexpressions.html) -- A paper written for extra credit in my undergrad. It details the dangers of microexpressions and how most of the research currently is not very robust.
* **June 5, 2022:** [Specks of Time](diary/specks-of-time.html) -- My first blog post reflecting on the movie *Everything Everywhere All at Once*.
:::