---
title: "gallery ✦ arka ruins"
output: 
  html_document:
    fig_caption: FALSE
    includes:
      in_header: header.html
      after_body: footer.html
css: "indexstyle.css"
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(pixture)
```


::: {.container class="fluid-row d-flex flex-wrap align-content-stretch"}
```{=html}
```{r, echo=FALSE, results='asis'}
xfun::file_string('menu.html')
```
```

This is an attempt at compiling (most) of my artistic efforts. I started actually writing this page in February 2024, and the last time I updated this page was `r format(Sys.time(), '%B %d, %Y')`.

::::{.col-md-12}

## colored
```{r, echo=FALSE}
paths <- c(
  "art/02-04-2024 allysol.png",
  "art/01-17-2024 lidelle.png",
  "art/01-02-2024 dragon ayasig.png",
  "art/10-01-2023 veriteth.png",
  "art/oc cygnus full.png",
  "art/other afri bday.png"
)

library(pixture)
pixgallery(paths)
```

## sketches
```{r, echo=FALSE}
paths <- c(
  "art/rkgk/08-21-2023 sona.png",
  "art/rkgk/08-21-2023 ophin painting.png",
   "art/rkgk/08-12-2023 teth.png",
   "art/rkgk/06-30-2023 moira doodles.png",
  "art/rkgk/06-15-2023 oc pokesona.png"
)

library(pixture)
pixgallery(paths)
```
::::
:::